name: superset
description: A modern, enterprise-ready business intelligence web application
category: analytics
logo: https://github.com/apache/incubator-superset/raw/0.38/superset-frontend/images/s.png
repository: open-datastudio/superset
